blank_issues_enabled: true
contact_links:
  - name: 🗯 Discussions forum
    url: https://HLasse/textdescriptives/discussions
    about: Usage questions, general discussion and anything else that isn't a bug report or a feature request.
  - name: 📖 TextDescriptives usage guides & package references
    url: https://HLasse.github.io/textdescriptives/
    about: Everything you need to know about textdescriptives and how to use it.
  - name: 🛠 Submit a pull request
    url: https://github.com/HLasse/textdescriptives/pulls
    about: Did you spot a mistake and know how to fix it? Feel free to submit a PR and contribute!
